spring:
  application:
    name: CRUD-department
  datasource:
    password: 9109477047@ybl
    url: jdbc:mysql://localhost:3306/Department
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true